### ISSUE TITLE
Add some specific logic to resolve and reject for request calls from the creative

### ISSUE THREAD

**Issue by ryanthompson591** [InteractiveAdvertisingBureau/SIMID#110]
The spec needs to specify what happens when the video element is already doing something and it is replying to a request.

For example:
SIVIC:creative:requestPause is called but the player is already paused.

The player should resolve in that case.  To put it in context:  the HTML5 video element returns a promise when you call play, but if the requested video is playing already, it will resolve the promise right away (not reject).

**Comment by andmig** [comment]
Resolved in 1.0.1
