### ISSUE TITLE
Cross-platform navigation: window.open is browser-specific API

### ISSUE THREAD

**Issue by gasperk** [InteractiveAdvertisingBureau/SIMID#112]
In MRAID spec we decided to go with `mraid.open` to avoid different ways of initiating navigation. Should we consider something similar in SIVIC? Right now the correct way to navigate is `window.open`, which might cause issues in cross-environment-ness of SIVIC. As in: can every environment detect and handle window.open call properly? 

If that's not the case, we perhaps have to inject a navigation function _into_ the creative iframe. The creatives would then have to call that function whenever they wanted to navigate.

**Comment by ryanthompson591** [comment]
This is going to get resolved in #232 as it relates to opening browsers on mobile platforms.
