### ISSUE TITLE
Messages sessionId meaning and clarifications required

### ISSUE THREAD

**Issue by andmig** [InteractiveAdvertisingBureau/SIMID#116]
Message `sessionId` property specs are prone to confusion. There is already session id that arrives with VAST. 
There are two options:
1. `Message.sessionId` is the same session id provided in VAST.
2. `Message.sessionId` is a unique to intrinsic player logic and it pertains exclusively to messaging protocol. In other words – it is an entity that stems from abstract messaging protocol rules only and has no connection to any other session ids that may be in play no matter context.
My vote is for enforcing `Message.sessionId` as an abstract entity. Messaging protocol values shouldn’t imply any other that specific to protocol meanings. If this is acceptable – we will have to create parameter in message `player:init` that communicates session id that originates in VAST.

**Comment by ryanthompson591** [comment]
I don't see a session ID in vast.  @andmig Can we close this issue?

**Comment by andmig** [comment]
Resolved
