### ISSUE TITLE
sending scroll/viewport position

### ISSUE THREAD

**Issue by gasperk** [InteractiveAdvertisingBureau/SIMID#145]
In order to do a scroll-reactive experience inside a sandboxed/secure iframe, you can use IntersectionObserver (where available). However, if SIVIC is to be adopted in environments that don't support that API directly (apps), we should consider introducing an abstraction layer where the SIVIC Player would read the coordinates in an environment-specific way, and send them to the creative in an environment-independent way. As an example, MRAID 3.0 has [`exposureChange`](https://iabtechlab.com/wp-content/uploads/2018/06/MRAID_3.0_FINAL_June_2018.pdf#page=60).

**Comment by ryanthompson591** [comment]
We decided to backlog this. Our feeling is that this will not be a commonly desired feature.
