### ISSUE TITLE
Example implementation should show how to preload Creative

### ISSUE THREAD

**Issue by advir1** [InteractiveAdvertisingBureau/SIMID#152]
https://github.com/InteractiveAdvertisingBureau/SIVIC/blob/5af81aa12157e4d4377455e7ba73fda184c3de52/examples/player/sivic_player.js#L62

This implementation does not touch the issue of preloading creatives. Since that would probably be the most common use case, we would at least need to demonstrate how that would work in theory, even just using one preloaded creative. I have a feeling that the state of the protocol object might become inconsistent when more than one creative is loaded at a time, since listeners are added only once while the target is changed on each creative load.

**Comment by ryanthompson591** [comment]
The sample does illustrate this.
