### ISSUE TITLE
SSAI and player to creative messaging

### ISSUE THREAD

**Issue by andmig** [InteractiveAdvertisingBureau/SIMID#163]
It seems we need to revisit messaging governance in SSAI use cases. It concerns mainly two message namespace groups: `tracking` and `video`.

From interactive ads adaption perspective, requiring certain features may trigger SIVIC perception as too difficult to implement and, thus, prompt publishers to avoid interactive video ads handling implementation.

### `tracking:` messages

In a nutshell, the default behavior in SSAI is that VAST trackers are reported server-to-server. The flipside of it is that, most plausibly, server will not communicate to video player VAST trackers reporting occurrences. 

As a side note, even if, for whatever reason, publishers do elect to notify client side about trackers reporting, discrepancies will be organically significant. This, in turn, makes strong argument against engaging publisher's client side into standard trackers reporting altogether. 

If SIVIC specs address the assumption that, at least in many SSAI cases, VAST trackers will **not** be reported to client, messages with namespace `tracking:` become optional.

### `video:` messages

Messages with namespace `video` may be too cumbersome to implement in SSAI. Since there is no native capacity for <video/> tag to expose video metadata, video player player (as a system that involves both client and server sides) will have to jump through the hoops to:
 1. detect ad video segment beginning and end and
 1. translate video stream actual timestamp into ad video timestamp in cases of mid and post roll ads.

As with `tracking:` messages we may allow for only subset of `video:` messages if not for publisher voiding video state events reporting at all with SSAI situations.

**Comment by ryanthompson591** [comment]
I think this issue is resolve because we no longer tell the player anything at all about how tracking is done.  We've removed the section where the player reports tracking to the creative.
