### ISSUE TITLE
Suggested new Error codes

### ISSUE THREAD

**Issue by ryanthompson591** [InteractiveAdvertisingBureau/SIMID#177]
Some players might blacklist certain SIVIC ads if they are abusive in some way.  So I suggest two error codes, with an explanation:
1. Creative blacklisted
- The player does not allow playback of this creative.  It could be because of abusive or buggy behavior.
2. Creative not on whitelist
-The player only supports a creatives on a whitelist.  This creative is not on this list.

**Comment by ryanthompson591** [comment]
Against:
This may not be in the spirit of SIMID as these choices should be made server side rather than client side.

Pro:
There is also a danger in not allowing these error messages in that if these errors do occur the publisher will have no way to let the creative know why it didn't render.

**Comment by mimidden** [comment]
May address later if it becomes an issue.
