### ISSUE TITLE
Questions/ suggestions regarding the spec

### ISSUE THREAD

**Issue by rgulrajani** [InteractiveAdvertisingBureau/SIMID#180]
1.	We have ads that are 15 seconds of video, and then 15 seconds of  javascript/html. There’s an “AdLeanIn”  to handle this use case, but it’s an unclear spec. Suggested spec: The player should call stopAd() when the ad has played for it’s full duration, not when videoComplete occurs. The spec should explicitly state that the ad duration should be the video duration + the end card duration. 
2.	Does the video proxy have two sets of methods: pauseAd/resumeAd and pause/resume?  Both are in the docs.  
3.	In-app mobile players should be forced to call pauseAd() when the app is backgrounded (when the home button is pressed, or when a call comes in, etc). And resumeAd() when the app is foregrounded. (This was an issue with VPAID as well.)
4.	Pause on clickthru should be allowed for all mobile in-app players since the app will be backgrounded.

**Comment by andmig** [comment]
The spec resolves the issue.
