### ISSUE TITLE
Consider submitting video state with every video message

### ISSUE THREAD

**Issue by pietermees** [InteractiveAdvertisingBureau/SIMID#188]
## Problem description
When the creative receives a video event such as `pause` or `ended`, it currently can't know the state of the video element at the time this event was generated.

Several workarounds were proposed, none of which seem to fully address the problem:

### `getVideoState` workaround
The creative has the option to fire a `getVideoState` event back, and wait for the response. But the state that will result from this call will be different from the state at the time of the original event. For example, when the messaging latency between the frames is large (in the hundreds of milliseconds), the flow would be:

| Time | Video `currentTime` | Player | Creative |
|---|---|---|---|
| `0` | `1000` | send `pause` | |
| `100` | `1100` | | receive `pause`, send `getVideoState` |
| `200` | `1200` | receive `getVideoState`, send response | |
| `300` | `1300` | | receive video state |

**The creative will assume the `pause` event happend at `currentTime=1200` while it actually was `currentTime=1000`.**

### Listening for state events workaround
Another approach is to have the creative listen to all state changes like `timeupdate` and maintain its own representation of what it thinks the video state is. The challenge here is that
1. State changes are not continuously fired, for example `timeupdate` only fires every 250ms, so you don't have full granularity.
2. We're not forwarding all media events to the creative, so it might not be receiving all state updates.

| Time | Video actual `currentTime` | Player | Creative | Creative assumed `currentTime` |
|---|---|---|---|---|
| `-200` | `800` | send `timeupdate` | | `550` |
| `-100` | `900` | | receive `timeupdate` | `800` |
| `0` | `1000` | send `pause` | | `800` |
| `50` | `1050` | send `timeupdate` | | `800` |
| `100` | `1100` | | receive `pause` | `800` |
| `150` | `1150` | | receive `timeupdate` | `1050` |

**The creative will assume the `pause` event happend at `currentTime=800` while it actually was `currentTime=1000`.**

## Proposed solution
The proposed solution is to have the player take a snapshot of all the video state and send it with every video event. We've already defined this state as part of the [`getVideoState` `resolve` message](https://interactiveadvertisingbureau.github.io/SIVIC/#sivic-creative-getVideoState-resolve)

This has the benefit of
1. making sure you have the most accurate state information every time you handle a video event
2. simplify the creative-side implementation as you no longer need to maintain your own representation of the video state, which is something that basically every SIVIC creative would have to do so a lot of duplicated work with risk of mistakes
3. it might allow us to reduce the API surface by removing the `getVideoState` message, although there's an argument to be made that you might still want to be able to query the video state outside of the video events

**Comment by amitshetty** [comment]
Decided we don't want to do this. Might be unnecessary.
