### ISSUE TITLE
Clarify whether variableDuration indicates player or ad capability

### ISSUE THREAD

**Issue by pietermees** [InteractiveAdvertisingBureau/SIMID#20]
https://github.com/InteractiveAdvertisingBureau/SIVIC/blob/0d27b07696f94099e8f88867b7b1b701f1cfd781/index.bs#L238-L241

Andrei Andreev
10:58 PM Mar 4
Need further articulation. Is it attribute provided in VAST as it describes ad capacities or is it something that flags player capacities.
Traditionally VPAID ads do offer extended duration. Player doesn't have to call stopAd in such cases.

It feels the value of such property is rather for player communicating to interactive portion whether it respect extended user experience beyond video duration.
Show less
Pieter Mees
Pieter Mees
7:28 PM Mar 22
Agreed, it sounds more logical that the player signals to the ad whether or not extending duration is allowed. If the ad needs to know this before buying the impression, then it should be flagged on the bidding side before the impression is bought.
Michael Tuminello
Michael Tuminello
8:43 PM Apr 13
True. The thinking is that the VAST should communicate its expectation that the video can run over the allotted duration so the player can potentially choose not to run it, just like players sometimes use duration to decide if a standard video is unsuitable.

**Comment by andmig** [comment]
Resolved - spec is considered clear.
