### ISSUE TITLE
Diagram for Introduction section showing separation of media and interactivity

### ISSUE THREAD

**Issue by aronschatz** [InteractiveAdvertisingBureau/SIMID#203]
https://docs.google.com/document/d/12QcpSqtqTxvTXMsb9gPtaKKWJJSdE3Ak2HoIGJ8kd_o/edit#

A diagram is needed for Section 4 to show that SIVIC separates the media asset and the interactive asset and the player combines them to present to a consumer.

@graphicdeveloper I can probably explain this better, if needed. Let me know.

**Comment by graphicdeveloper** [comment]
OK, after a _looooooong_ delay, I *finally* got the 4th and last major diagram for the SIMID spec finished tonight, woohooo!!!! Here it is - I hope you like it!
![SIVIC_API_Model_9C](https://user-images.githubusercontent.com/453789/60247066-cf1e2b80-9874-11e9-9332-e18747768d35.png)

**Comment by graphicdeveloper** [comment]
I added some additional text to the main titles of each box, for greater clarity.
![SIVIC_API_Model_9C](https://user-images.githubusercontent.com/453789/60250658-e7de0f80-987b-11e9-93e1-2f949755a790.png)

**Comment by andmig** [comment]
Final diagrams are approved by the group.

**Comment by ftslo** [comment]
Sorry, i only saw that this issue was closed the other day. I was wondering if there's any value in adding a layer above the iframe layer in the diagram to make it explicitly clear that the Player's video controls actually live on the highest z-ndex? 

I've encountered many players that work this way (auto-hiding controls) which effectively block user interaction with the SIMID creative overlay.

**Comment by graphicdeveloper** [comment]
Hey there. It's definitely fair point, but in the interest of simplicity I decided not to go there. I think most developers who read the spec will know what their technical options are related to z-index layering of assets/controls - and for the wider business-oriented audience it would just add potential confusion. I went with simplicity for the sake of focusing on the main idea, which is that the SIMID iframe is above the video content in a separate and sandboxed layer. Thanks for the feedback!

**Comment by ftslo** [comment]
I completely understand/respect the decision to go with simplicity. 

However, I might disagree with the point about developers being familiar with technical options. 

Creative developers (and designers) of VPAID units that I've encountered do not often have sufficient familiarity with the wide array of differences between Video Players across different publishers. Often VPAID ads are designed and built without knowledge of the media buy and no reliable reference about where Video Player controls may be located. 

It's hard for Creative Developers to anticipate that publishers make controls available to users during ads, when the VAST/VPAID testers don't have overlaid controls:
https://www.disney.com/

It also doesn't really help that most available VPAID testers do not account for controls that overlay and interfere with creative UI:

https://developer.jwplayer.com/tools/ad-tester/

https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector

https://validator.beachfront.io/

http://tools.springserve.com/tagtest

https://flowplayer.com/help/tools/ad-tester

http://tagvalidator.tremorvideo.com/

https://tester.zentrick.io

https://preview.tremorvideodsp.com/#/

http://demo.theoplayer.com/advertisement-tester

https://tester.doubleverify.gent/#/

http://demo.theoplayer.com/advertisement-tester

Perhaps there's a mention of best practices attached to an asterisk somewhere that could alert readers to be mindful of this?

**Comment by graphicdeveloper** [comment]
Well that opens up a whole other can of worms. There's no scalable way the spec could anticipate or account for the countless variations of custom video player UI out there (in text much less as a diagram). In the simplest case, the browser will render the native controls flatly on the video content itself, so the diagram is correct for the default case. I'm not sure how we could do much more without having to write a whole new section or even separate document.

...Maybe this is an opportunity for a resourceful and motivated developer such as yourself to write a stand-out blog post on the topic? ;-)

**Comment by ftslo** [comment]
Thanks for the chat, I think the idea of communicating this (and similar ideas) via a blog post or best practices is great. As long as the information is accessible it can only be beneficial.
