### ISSUE TITLE
VAST working group proposal

### ISSUE THREAD

**Issue by ryanthompson591** [InteractiveAdvertisingBureau/SIMID#210]
I suggest we send this to the VAST working group.

To the VAST working group,
We would like to add a new standardized tracking event.
InteractiveStarted

This event should be fired to indicate that an interactive creative has started.

Some details:
- Since video playback and interactive playback now happen in parallel in 4.1 we need a way of tracking interactive start which might not happen at the same time as video start.
- We want this as a standardized event instead of custom event
  1. Wrappers will be able to track the event
  2. Buyers and sellers can validate metrics with a standardized event
- We would prefer to call this InteractiveStarted instead of impression to avoid confusion
- We don't think this should be a child of InteractiveCreativeFile because it will make it hard for wrappers to add tracking
- The SIVIC spec will specify exactly when this event should be fired.
- The event can be used by non SIVIC creatives, but they will need to specify when it should be fired for their use cases.

**Comment by ryanthompson591** [comment]
FYI, I just checked through the most recent VAST document and this is not in 4.2.

**Comment by aronschatz** [comment]
I'll insert it later today.

**Comment by aronschatz** [comment]
https://docs.google.com/document/d/15u4vL95vlelX6NWc4pfMmttcwf7NpOE0hus51FWRFw0/edit#

Section 3.14.1 has InteractiveStart. @ryanthompson591 Please check and close if good.

**Comment by aronschatz** [comment]
I made some edits to that, too.

**Comment by aronschatz** [comment]
This was accepted on the VAST working group call.
