### ISSUE TITLE
Explicit Guidance to address the use case of Creative Embedded Ad Video

### ISSUE THREAD

**Issue by ftslo** [InteractiveAdvertisingBureau/SIMID#212]
When the ad video is rendered into the _Video Player context*_, the Player is fully aware of the video events and the player's control are in sync with the video state (playback status and volume).  

With VPAID, it's not uncommon for the advertiser to leverage the primary ad video as a creative element w/in the _creative context*_ of the VPAID unit. 

This gives the VPAID ad much greater flexibility for interesting interaction and visual appeal, ie: video selectors, resizing ad video, layered backgrounds behind the video, etc... 

These effects are achieved by inserting the ad video asset within a <video> element that is added to the DOM of the interactive creative layer (the _creative context_). Unfortunately, this type of execution leaves room for the Video Player and the ad video state to fall out of synchronization as the video player does not actually load the video asset.

I believe that without a clear path to achieve this type of use case the SIVIC format may suffer from 'less than best practices' which have historically resulted in communication breakdown between the VPAID unit and the Video Player (and thus poor user experience, advertiser and/or publisher brand image concerns).

If this use case is not clearly defined or supported, it might also become a barrier for adoption if VPAID will support it but SIVIC will not. Since this has been a clear use case for VPAID, does it make sense to provide specific guidance for it so creative developers can work within defined guidelines of the SIVIC spec?

![creative_embedded_ad_video](https://user-images.githubusercontent.com/6226327/53424380-14a71680-39b1-11e9-8883-b73f59413749.png)

TERMINOLOGY
**VPAID unit**: An ad unit comprised of two components: 1) a primary ad video asset (media file) 2) an interactive html creative unit with its own DOM (and associated assets) which is rendered into the html environment that overlays the Video Player

**Creative Context**: The DOM of the interactive html creative component of the VPAID unit

**Video Player Context**: The html environment provided by the Video Player for rendering the ad video asset

**Comment by ftslo** [comment]
Apologies for the delay @amitshetty . This is an example of the type of VPAID unit which implements creative embedded video: https://tinyurl.com/y4f9kh26

Clicking on the 'Rich Interaction' button demonstrates the type of capability that this type of VPAID implementation seems to be favored with creative agencies from what I've seen.

I don't understand how this type of feature or functionality would be supported in SIMID, but I wanted to raise it as a real use case which I suspect may lead to some users to choose VPAID over SIMID for creative storytelling capability.

**Comment by amitshetty** [comment]
Seems like we have the features needed. requestchangeadduration can be used. and requestresize was also added. 
@ftslo - any chance you can build out a sample ad and add to the examples? Thanks!
