### ISSUE TITLE
How can opening clickThruUrls be handled across mobile/web environments

### ISSUE THREAD

**Issue by graphicdeveloper** [InteractiveAdvertisingBureau/SIMID#232]
Interactive Creatives (SIVIC ads) may load and run in **either** a traditional web browser environment (desktop / mobile web), **or** a WebView environment (mobile apps / OTT apps / etc.). These 2 different environments present a challenge around offering a single, unified way of opening a new window to visit a clickThruUrl from SIVIC:

- Modern browsers will block a new window/tab from being opened programmatically by a Player unless there's a _synchronous_ user click directly triggering that action, but the SIVIC PostMessage API is _asynchronous_ by design. Thus, _the creative_ should open new clickThru windows when running in a browser - requesting a new window be opened by the player via PostMessage will likely be frustrated by browsers' pop-up blocking logic.

- Mobile App and OTT environments don't make it easy for a creative to reliably open a new WebView (for various technical reasons based on platform). Thus, _the player_ should (must?) be responsible for opening new clickThru WebViews when a SIVIC creative is running in an App environment.

@aronschatz Mentioned that the MRAID group grappled with this issue already, and added the `mraid.open` method to that API/SDK to support mobile environments - their approach may be instructive for this group. From the MRAID spec (page 25):

> **open** method
The open method will display an embedded browser window in the application that loads an
external URL. On device platforms that do not allow an embedded browser, the open method
invokes the native browser with the external URL.

SIVIC operates in an iFrame, which presents additional complexity not faced by MRAID. Nonetheless the problem is similar, and maybe we can offer something similar in SIVIC.

This issue was discussed on today's SIVIC workgroup call, but we didn't reach any decisions about how to resolve it. Hopefully we can discuss it here and come up with a good solution.

**Comment by ryanthompson591** [comment]
This is handled in issue #299
