### ISSUE TITLE
Add support for player handled links

### ISSUE THREAD

**Issue by aronschatz** [InteractiveAdvertisingBureau/SIMID#239]
In environments that the player MUST handle outbound links (in-app), the player must be able to signal to the creative that it will be handling clicks and that the creative must tell the player where to navigate to.

My suggestion (names can be decided)

1. Add a flag in environmentData (or otherwise in the initialization) that states the player will handle the outbound link or not.
2. Add a method to tell the player the outbound link that needs to be opened.

**Comment by ryanthompson591** [comment]
Merging this with #299
