### ISSUE TITLE
Remove information available via macros

### ISSUE THREAD

**Issue by aronschatz** [InteractiveAdvertisingBureau/SIMID#243]
SIMID provide a mechanism for having the player send tracking events and expanding macros. The SIMID creative should not need direct access to them and always should rely on the player... To this end, there are a few variables to remove...

In CreativeData
-adId;
-adServingId
Discussion is needed about creativeID.

In EnvironmentData
-siteUrl
-appId
-useragent
-deviceId

**Comment by ryanthompson591** [comment]
Lets remove this before we release 1.0, once its in there its harder to take out than put in.

**Comment by aronschatz** [comment]
Let's discuss what's needed and what needs to be removed in the upcoming meeting and then I'll do a PR.

**Comment by aronschatz** [comment]
@andmig Can you comment on the original post of this ticket? I can create a PR to remove everything listed. I just need confirmation from someone else that there's no reason to have the things listed.

**Comment by andmig** [comment]
1. As far as Creative Data is concerned, there is no need for special handling as VAST owner can always write the desirable data into AdParameters node.

1. Environment variables a different set. This is something that is known and can be provided by individual site only. The parameters listed in Aron's post are highly valuable for both DCO and measurements. So, they should not be removed.

**Comment by aronschatz** [comment]
https://github.com/InteractiveAdvertisingBureau/SIMID/pull/279

Closing this. Will use the PR to track instead.
