### ISSUE TITLE
Nonlinear creatives examples

### ISSUE THREAD

**Issue by davidthibault** [InteractiveAdvertisingBureau/SIMID#249]
Hello,
Can you provide guidelines, tutorials or examples for implementing nonlinear creatives ?

Thanks you.

David.

**Comment by ryanthompson591** [comment]
Right now SIMID doesn't support non linear ads.  This is not because we
don't think the standard can support non linear.  It is because VAST does
not allow interactivecreativefile in the non linear section.

Look up 3.12.1 and look at sub elements.  You can still put an iframe as
non linear.  would that be adequate for your use case?

https://iabtechlab.com/wp-content/uploads/2018/11/VAST4.1-final-Nov-8-2018.pdf

**Comment by davidthibault** [comment]
Thanks for your response. 
We have pushed a lot to keep the non linear support and it seems to have changed in VAST 4.2 : https://iabtechlab.com/wp-content/uploads/2019/04/VAST_4.2_final_23April2019.pdf
See the note on page 11 
“Note - based on feedback received during public comment, the group decided not to deprecate nonlinear ads in VAST 4.1.” 

Do you think SIMiD will never support non linear ?

Regards.

**Comment by ryanthompson591** [comment]
We've discussed non linears in group.  Our feeling is that there would need
to be some changes to the spec for non linear.  It's unclear to me if the
changes will be trivial or not.

I suppose other than the ability to pause playback, what does SIMID really
accomplish that an iframe non linear cannot?

My assessment is that in order for SIMID to support non linear it will need
a champion.  Someone with a vision of what non linear SIMID should be.
1. Should it take up the entire viewing area like linear SIMID does? Would
publishers accept that?
2. What control over the player should it have? Publishers may feel
differently about an ad pausing content playback than they feel about an ad
pausing its own playback.
3. Why is it different from a non linear iframe?
4. Should it maybe start at some smaller dimension and be allowed to ask to
expand?

David.  Could you be that champion?  If so join us Thursday afternoon
sometime and pitch it!  Seriously though, the group is small and we don't
really have any non linear folk on it.

**Comment by davidthibault** [comment]
Hello Ryan,
I could participate, but I am located in France, so it would be remote and with a six-hour time difference.
Maybe I could send you an email with our recommendation, and some existing live examples we have with some publishers.
What do you think ?

**Comment by ryanthompson591** [comment]
I think the groups would be fine with that.  I have to warn you that email
only can be slow.

**Comment by davidthibault** [comment]
To explain a bit more, non linear creatives are very usefull for mainly two usecases (and maybe more) : 
TV channel use a lot our technology to monetise livestream for example. They don't want to cut the live stream. And one preroll to monetize a 2 hour live stream is not enough.
We have also some publishers that have a lot of short videos, and they don't want to use a preroll with a longer duration than the editorial content.
That's why non linear ad are still usefull.

And communicate with the main player help the creative to be a better one. Especially, if the creative can have access to the current time, and the duration, it can display at the best timecode.
If it can access to streamSize and position, it will position in a better way.
With these feature we can do creatives like that : https://dip5sgyvj5owd.cloudfront.net/15147/assets/djazuay-output-720-auto.mp4 (if you want I can send you non linear VAST/VPAID file to show you it is real).

The creative could also give orders to the content player. The publisher could accept or not of course. But if it is possible to ask to play/pause, to mute/unmute or even to resize, it could allow great creative like that : https://dip5sgyvj5owd.cloudfront.net/15097/assets/fsvrfaz-output-720-auto.mp4

I can still join you (remotely) if you want this Thursday, but maybe it is too late. Please let me know. 
And even if it is not possible this Thursday, I could be the non linear champion with pleasure.

Regards.

**Comment by ftslo** [comment]
@davidthibault ,

Would you be able to provide a live example of the format demonstrated in this video:
https://dip5sgyvj5owd.cloudfront.net/15097/assets/fsvrfaz-output-720-auto.mp4

It looks similar to the type of execution raised in this issue: https://github.com/InteractiveAdvertisingBureau/SIMID/issues/212

**Comment by ryanthompson591** [comment]
I've marked this issue for discussion at the next meeting.

**Comment by davidthibault** [comment]
> 
> 
> I've marked this issue for discussion at the next meeting.

Tha

**Comment by davidthibault** [comment]
> 
> 
> I've marked this issue for discussion at the next meeting.

Thanks.

**Comment by davidthibault** [comment]
> 
> 
> @davidthibault ,
> 
> Would you be able to provide a live example of the format demonstrated in this video:
> https://dip5sgyvj5owd.cloudfront.net/15097/assets/fsvrfaz-output-720-auto.mp4
> 
> It looks similar to the type of execution raised in this issue: #212

Hello @ftslo,
I have just look at the post you mentioned. I totally agree with the need of being able to control the main video player. The suggestion of @ryanthompson591 on this, the requestResize command, would be a good solution. 
In our side, for linear creatives (preroll) with a custom video size, we use a dummy video into the Video Player, while the actual ad video asset is played within a video element created inside of the creative : 
https://vast.adpaths.com/lWkSW0n => 
https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector?tag=https%253A%252F%252Fvast.adpaths.com%252FlWkSW0n

But in this topic I would like to speak about non linear creatives, I really think It would be nice to have the same option to reduce the main video stream (once again, the publishers could or not obey to these orders).
https://contents.adpaths.com/v3/stream-reducer/premium/index.php?publicationId=ny2j9KJ => 
https://www.adways.com/demo/magic-code?player=jwplayer7&vasttype=nonlinear&vast=https%3A%2F%2Fcontents.adpaths.com%2Fv3%2Fstream-reducer%2Fpremium%2Findex.php%3FpublicationId%3Dny2j9KJ (press play and wait for 4 secondes). 
In this example : 

- the main video plays, 
- the adcall is done 
- the vpaid, once loaded, ask to resize the main video
- the ad is displayed

Once again, I am available to discuss on it.

**Comment by amitshetty** [comment]
Hi David - I think it will be great to have you on a call and present the use case in more detail to the working group. I will reach out to you off line via email to schedule a call at a time that works for you.
Thanks!
Amit

**Comment by davidthibault** [comment]
> 
> 
> Hi David - I think it will be great to have you on a call and present the use case in more detail to the working group. I will reach out to you off line via email to schedule a call at a time that works for you.
> Thanks!
> Amit

Thanks Amit

**Comment by davidthibault** [comment]
Hi all,
I see in this discussion : https://github.com/InteractiveAdvertisingBureau/SIMID/issues/161
> This is most recently discussed in #249.
> I think the consensus was to add non linear in SIMID 2.0.

Does it mean that nonlinear is not supported yet in the current version of SIMID ?

Regards ?
