### ISSUE TITLE
Clarify and confirm proposed creativeData ids

### ISSUE THREAD

**Issue by pietermees** [InteractiveAdvertisingBureau/SIMID#25]
https://github.com/InteractiveAdvertisingBureau/SIVIC/blob/0d27b07696f94099e8f88867b7b1b701f1cfd781/index.bs#L278-L285

- `adId`: Is this Universal Ad ID or the id attribute of the <Ad> node?
- `creativeId`: Assuming this is the "id" attribute of the <Creative> ?
- What is the justification? Since ad server constructs AdParameters node, isn't this information readily available to the ad script?

**Comment by ryanthompson591** [comment]
This is now more generally covered in #243, which is blocking release (so I think it will be covered).
