### ISSUE TITLE
Message SIMID:Creative:fatalError may need resolve response

### ISSUE THREAD

**Issue by andmig** [InteractiveAdvertisingBureau/SIMID#252]
Since the player has an option to stop ad altogether or not - message ~resolve/reject~ is needed. The resolution will indicate to creative how player decided to proceed.

**Comment by amitshetty** [comment]
Q - if creative calls fatalError and player responds with reject?

**Comment by ryanthompson591** [comment]
See section 7.3.5. Ad Errors Out
That goes over current workflow.

**Comment by andmig** [comment]
Resolved
