### ISSUE TITLE
SIMID:Player:init "resolve" needs time constraint

### ISSUE THREAD

**Issue by andmig** [InteractiveAdvertisingBureau/SIMID#253]
The player cannot wait indefinitely. We must specify how long the player should wait for.

In essence, resolve coming from creative is an indication of creative readiness. 

Proposed timeout is 1000ms.

**Comment by ryanthompson591** [comment]
I think we had a timeout discussion in the past, I was pushing for 2 seconds.  1 second might be too short for high latency situations like mobile or satellite connections.

The ideal would be to give the creative adequate time, but get rid of creatives that are hanging or acting poorly.

**Comment by amitshetty** [comment]
Add to best practices? Base it on publisher's data since they do want to play the ad...

**Comment by amitshetty** [comment]
Do we need a timeout error in VAST?

**Comment by andmig** [comment]
Resolved in 1.0.1
