### ISSUE TITLE
Messages Sequence Diagram

### ISSUE THREAD

**Issue by andmig** [InteractiveAdvertisingBureau/SIMID#256]
Below is a diagram that illustrates all messages in the spec. This is **not** a candidate for inclusion into the documentation. The purpose of the diagram is to serve as a blueprint for the diagram that replicates the similar one in VPAID spec. In particular, it attempts to categorize the messages. The region in this diagram can be candidates for separate focused compartments. 

![SIMID Messages Sequence](https://user-images.githubusercontent.com/39165043/59291335-9bbe8880-8c48-11e9-83c2-27eec0f662a4.png)

**Comment by amitshetty** [comment]
Thank you Andrei! Will post on slack too so people comment.

**Comment by amitshetty** [comment]
<img width="688" alt="Screen Shot 2019-06-06 at 11 51 46 AM" src="https://user-images.githubusercontent.com/2042189/59058484-98df2480-8851-11e9-833e-99542562fdb5.png">

**Comment by graphicdeveloper** [comment]
Hey guys, sorry for the delay on this! I have not forgotten and am planning to get these done this weekend, just been a hectic couple of weeks.

**Comment by andmig** [comment]
1. The initial diagram is updated to eliminate precise timeout values.
1. Below are four diagrams. Each diagram represents a region of aggregated (original) one. Diagram title describes messages categories.
1. We may want to have the final visuals to be split by message category. This will make it more readable and **more printable**. As for printable - original diagram will not definitely fit into a page.

![SIMID Messages Sequence  Initialization](https://user-images.githubusercontent.com/39165043/59291569-361ecc00-8c49-11e9-94d7-c2c524401e1f.png)

![SIMID Messages Sequence  Player State Change Requests](https://user-images.githubusercontent.com/39165043/59291584-3e770700-8c49-11e9-83f2-642e2c0795a6.png)

![SIMID Messages Sequence  Information Massages](https://user-images.githubusercontent.com/39165043/59291598-446ce800-8c49-11e9-95fd-63dd14bc4174.png)

![SIMID Messages Sequence  Ad End Messages](https://user-images.githubusercontent.com/39165043/59291610-4afb5f80-8c49-11e9-9d1f-939444ee6ce2.png)

**Comment by graphicdeveloper** [comment]
Hey guys. I'm nowhere near done on these, but this is a first pass at taking _some_ of the above diagrams and restyling them to look like the other diagrams visually. We can discuss on tomorrow's call - I have questions.
![SIMID_Events_Diagram_1A](https://user-images.githubusercontent.com/453789/59415541-85174f00-8d78-11e9-9581-ddcaabf548c7.png)

**Comment by graphicdeveloper** [comment]
I'll break this up into multiple diagrams and add the rest of the messages once we figure out how we want to organize these within the spec, etc.

**Comment by ryanthompson591** [comment]
Discussed in meeting.

Lets do diagrams for paths:
1. Initialization/start
2.Unload/stop
3.skip
4. Ad Errors out

Lets have separate diagrams for each of these and then place them in the appropriate section.
Note: substitute word ad for creative?  -Maybe if possible with layout-

Other possible diagrams (less high priority):
1. Initializing times out /errors out
2. Some sample messages like going full screen.

Action items: David to create pull requests.

**Comment by andmig** [comment]
Closing - diagrams are addressed.
