### ISSUE TITLE
requestFullScreen resolve vs. Player.resize

### ISSUE THREAD

**Issue by andmig** [InteractiveAdvertisingBureau/SIMID#258]
Entering full screen mode entails ad resize. Does player have to report `Player.resize` message to creative? 

If we assume that `resolve` is sufficient - does it mean creative will have to calculate dimensions internally?

**Comment by gasperk** [comment]
Entering fullscreen might result in a resize, but not necessarily so (maybe the creative is already as big as the screen). I think resolve/reject is only for entering a different mode and resize should still come if there's an actual change of size.

**Comment by andmig** [comment]
Discussed. Not important in this iteration.
