### ISSUE TITLE
environmentData -> adPauseAllowed?

### ISSUE THREAD

**Issue by pietermees** [InteractiveAdvertisingBureau/SIMID#26]
**Amit Innovid**
I'm wondering about the following additional parameters:
- `adPauseAllowed` - specifically in live streaming we may not want to allow ad pause at all, in which case the creative should be informed on init?
- `adSkippable` - whether or not the creative may skip the ad

**Ryan Thompson**
I agree with `adPauseAllowed`. What do you think of just sending the skipOffset from vast in to the vpaid ad. Who should be responsible for skipping should it be the vpaid exclusively?

**Michael Tuminello**
MRAID has an env var for COPPA - do we need it?

**Pieter Mees**
`skippableState` seems to be already a property in the environment data?

**Comment by ryanthompson591** [comment]
this is now only variableDurationAllowed and skippableState.    I'm closing this as being obsolete and probably fixed.
