### ISSUE TITLE
Why Player:appBackgrounding needs resolve?

### ISSUE THREAD

**Issue by andmig** [InteractiveAdvertisingBureau/SIMID#264]
Since neither player nor app can override backgrounding - what is the point for the creative to send `resolve` or for the player to wait for it? In other words, are there any consequences on the player side of resolve?

On the other hand - appForegrounding does not have `resolve`.

As with `appForegrounding`, `appBackgrounding` message should be information-only.

**Comment by gasperk** [comment]
Agreed, this is informational only, creative (or even app) can't affect the outcome, don't even have time to react, and therefore the message shouldn't require or expect a response.

**Comment by andmig** [comment]
Discussed. Response `resolve` is deprecated.
