### ISSUE TITLE
Message Creative:requestChangeVolume issues

### ISSUE THREAD

**Issue by andmig** [InteractiveAdvertisingBureau/SIMID#272]
1. Needs a short intro to the message purpose.

1. Sentence _"...creative wants the **volume** muted"_ is incorrect. The volume is an entity that has a value from 0 to 1. The term `muted` related to the state of media audio, which is unrelated to `volume` state. Specifically, the volume can be greater than 0 while audio is muted - **this is the main reason for the objection**. Also, the word `wants` is animalistic. 

    The sentence should read _"... creative requests ad media to mute"_

3. Parameters should be represented in a form of data type visualization conventions of this document.

4. Sentence _"muted(boolean): True indicates the creative wants the volume muted."_ 
a) In JavaScript, the value of Boolean is lower case. Hence - it is `true` - not `True`
b) If param `muted` is required - it is either `false` or `true`; otherwise, the spec will benefit from the statement that absence of the parameter `muted` means the same as `muted = false`.

**Comment by ryanthompson591** [comment]
I agree.  Can we rework the wording in the new doc for this?

**Comment by andmig** [comment]
Resolved in 1.0.1
