### ISSUE TITLE
Diagrams :: Player Messages

### ISSUE THREAD

**Issue by andmig** [InteractiveAdvertisingBureau/SIMID#274]
Below are individual UML player messages diagrams. There are two types: communication and sequence diagrams for the same message. 

Please review.

![PlayerappForegrounding Communication](https://user-images.githubusercontent.com/39165043/59796899-82eb4e00-92ac-11e9-8652-ff9d91320bae.png)
![PlayerappForegrounding Sequence](https://user-images.githubusercontent.com/39165043/59796900-82eb4e00-92ac-11e9-8f29-2b8750daa5f5.png)
![PlayerfatalError Communication](https://user-images.githubusercontent.com/39165043/59796901-82eb4e00-92ac-11e9-9603-d8e82590a9f2.png)
![PlayerfatalError Sequence](https://user-images.githubusercontent.com/39165043/59796902-82eb4e00-92ac-11e9-9e8e-5a167a980a36.png)
![Playerinit Communication](https://user-images.githubusercontent.com/39165043/59796903-8383e480-92ac-11e9-870f-1e43f6e70554.png)
![Playerinit Sequence](https://user-images.githubusercontent.com/39165043/59796904-8383e480-92ac-11e9-8d4b-f3137dfa4c53.png)
![Playerresize Communication](https://user-images.githubusercontent.com/39165043/59796905-8383e480-92ac-11e9-9efb-fbea03960fe7.png)
![Playerresize Sequence](https://user-images.githubusercontent.com/39165043/59796906-8383e480-92ac-11e9-81fc-b47d775ce97a.png)
![PlayerstartCreative Sequence](https://user-images.githubusercontent.com/39165043/59796907-8383e480-92ac-11e9-8acd-700c69824cec.png)
![media messages communication](https://user-images.githubusercontent.com/39165043/59796908-8383e480-92ac-11e9-9ab6-1d55eb13dbcc.png)
![media messages sequence](https://user-images.githubusercontent.com/39165043/59796909-841c7b00-92ac-11e9-86b7-48bf9c5bfc72.png)
![PlayeradSkipped Communication](https://user-images.githubusercontent.com/39165043/59796912-841c7b00-92ac-11e9-8d0c-075df8f72761.png)
![PlayeradSkipped Sequence](https://user-images.githubusercontent.com/39165043/59796914-841c7b00-92ac-11e9-870e-962f08b57021.png)
![PlayeradStopped Communication](https://user-images.githubusercontent.com/39165043/59796917-841c7b00-92ac-11e9-933e-2477ad3fbf61.png)
![PlayeradStopped Sequence](https://user-images.githubusercontent.com/39165043/59796918-841c7b00-92ac-11e9-8cbe-5ebd5ccd2198.png)
![PlayerappBackgrounding Communication](https://user-images.githubusercontent.com/39165043/59796919-841c7b00-92ac-11e9-839a-b09e1bcd09cd.png)
![PlayerappBackgrounding Sequence](https://user-images.githubusercontent.com/39165043/59796920-841c7b00-92ac-11e9-8d03-122b9ed31cb7.png)

**Comment by andmig** [comment]
@graphicdeveloper Diagrams above are a response to your suggestion to implement visuals for all messages. please review.

Thank you.

**Comment by amitshetty** [comment]
I forgot to ask about this on the call today. Thoughts on this folks? And plan to include in the doc? :-)

**Comment by graphicdeveloper** [comment]
I am working on event flow diagrams for at least 4 primary use cases which we discussed a week ago (all within section 7). Beyond that, I wouldn't go as far as to say that every single thing merits a diagram, but if I have time I'm happy to produce style-consistent versions of whichever diagrams everyone things are most important.

I am still hoping/trying to complete work on the 1 big Diagram that's currently in the spec from Andre in a restyled form.

**Comment by andmig** [comment]
Resolved
