### ISSUE TITLE
Message Protocol Section (#4) is Confusing, Feels Out of Order

### ISSUE THREAD

**Issue by graphicdeveloper** [InteractiveAdvertisingBureau/SIMID#278]
I've raised concerns that I think the Message Protocol Section of the SIMID spec is confusing. Here are my primary concerns:

**A)** Section 4.2 (Transport Layer) feels like it's out of order. The sections don't build on each other progressively in an additive, logical way (each section building on the last). Rather, the **uninitiated** reader must jump around from section to section somewhat haphazardly to try to comprehend how it all works. To clarify:

1. Section **4.2.1** (_Establishing a new session_) --> depends on **4.2.2 B** (_Send an acknowledgement message_)
2. **4.4.2 B** --> depends on **4.2.2 A** (_Send a message_)
3. **4.4.2 A** --> depends on **4.3** (_Message Data Structure_), which is itself not explained until _after_ **4.2.3** (_Receiving Messages_)

To me it would be clearer if each section didn't come until after the things it depends on were already explained, for example:
4.2) Message Data Structure
4.2.1) _resolve_ Messages
4.2.2) _reject_ Messages
4.3.1) Send a Message
4.3.2) Receive a Message
4.3.3) Send an Acknowledgement Message
4.3.4) Establishing a New Session

That way each section would build on the concepts explained in the last, like a text book. For those of us who don't hold CS degrees I think it would make a lot more sense, and require less jumping around up and down between sections to make sense of it.

**B)** A question I have from reading _just_ this section of the spec, without looking at the code, is, "Does each party keep an independent numeric index of Message ID's, or do they both increment the same list (ie, no duplicate Message ID's)?" If they share the same ID list, how do you avoid both the player and the creative _ever_ sending different messages with the same ID at the same time?

**C)** In Section 4.2.2 B (_Send an acknowledgement message_), #3 is: `Add promise to the resolve list, annotated with sessionId and messageId`.  ...This is the 1st mention of **"resolve list"** - a concept that is only ever mentioned twice, and explained exactly *nowhere*. What is a new reader supposed to make of this? Why isn't it explained at all anywhere? Can we add this?

**D)** One more note - I think Section 4.1.1 (postMessage Transport) could use more than a single line of explanation. Many developer will be familiar with postMessage, but certainly not everybody. It's not the spec's job to teach JavaScript, but a little more explanation couldn't hurt, right? ;-)

**Comment by ryanthompson591** [comment]
I've started a rewrite.  See #289 

I think David and I have a similar philosophy about how to lay it out.

**Comment by andmig** [comment]
Resolved
