### ISSUE TITLE
Evaluating the best spec language for SIMID collaboration and documentation

### ISSUE THREAD

**Issue by jeffreytgilbert** [InteractiveAdvertisingBureau/SIMID#288]
This week, we discussed the topic of converting the documentation from bikeshed's mixed HTML+Markdown syntax to a purely Markdown format. Here's a brief recapping for those that missed todays chat.

Pros:
- Markdown is a low barrier to entry.
- Markdown is familiar for anyone contributing through github.
- Markdown is automatically converted/rendered to hosted documentation by github.
- Markdown is easy to set up via web apps for live previewing of changes or developing locally in an IDE plugin (VS Code, IntelliJ, etc).

Cons:
- Hinting/Linting related to generating "spec" documentation is lost, as MD is a generic doc generator.
- Spec docs generated are not understood by IDEs in either format (MD or BS), and so they can't be used for code completion.

Goals:
- Convey the integration narrative, not simply the interface spec. 
- Event flow diagrams and explanations of design intentions have value, so retain these.
- Empower the target consumer of this documentation to easily integrate versioned SIMID support in their players or ad creatives, potentially with type checking and/or code completion like TypeScript type definitions provide in IDEs.
- Spec collaboration should be second nature for implementers and collaborators who join the SIMID collaborative community. 

I called out a few possible formats for consideration, but this is far from an exhaustive list. Of note, TypeScript and TSDoc support with CommonMark is possibly the most valuable type of documentation that could be generated as tools like IntelliJ and VS Code would be able to consume the output easily. I haven't checked to see what is available in the live collaborative and preview sense related to these specs, but they're certainly popular and approachable enough for anyone who could be expected to contribute to SIMID. 

Please feel free to give thoughts and feedback on this topic. I've worked with all of this before, so I could be biased on the ease of adoption or the best tool fit here if there's something better anyone else knows about.

**Comment by aronschatz** [comment]
As discussed on the call, it would be helpful to pick a small subsection of the spec and write what the typescript (or other thing) would look like to spur more discussion.

**Comment by jeffreytgilbert** [comment]
Here's a sample implementation of typescript object definitions in action.

[example] https://pasteboard.co/IpElVAR.png "sample"

**Comment by ryanthompson591** [comment]
The consensus is for now we don't have the resources to move from bikeshed to markdown.  Since bikeshed is adequate we are going to stick with that.
