### ISSUE TITLE
Sever issue:: Session initialization specs contradictions

### ISSUE THREAD

**Issue by andmig** [InteractiveAdvertisingBureau/SIMID#290]
Section `4.3.6. SIMID:Player:init` states: 

> [player] might send SIMID:Player:startCreative immediately after SIMID:Player:init

This contradicts the session establishment governance. Section 6.1, point 4 requires creative to generate session id AND commands session id being written into `Player:init` `resolve` message.

So, if the player is allowed to post startCreative before resolve from creative arrives, another case of spec non-compliance occurs - the player is allowed sending the message without concrete session id.

We must mitigate this contradiction. We can take one of the following paths.

**Proposal 1**

Delegate session id generation to the player. Although we elected such delegation less than ideal, to accommodate SSAI use case, we may want to reverse the decision.

One of the cons of this proposal is that, still, there is no clarity in what the failure of `resolve` response means. Did creative enter erroneous state? In which case - is it safe to display the iframe and transmitting other messages?

**Proposal 2**

Forbid the player from both iframe rendering and any further communications with SIMID iframe, including posting SIMID:Player:adStarted and any other than `resolve' creative messages processing,  until creative transmits `resolve`, This approach seems to be the most universal logical unification of both typical and SSAI-type environments. 

The second bird we might kill with this stone is to clarify the role of the corresponding `resolve`. At present, there are no consequences of creative failing to report `resolve`. Again, with the second approach, because `resolve` is critical - player should assume internal creative failure.

**Comment by andmig** [comment]
I wrote a copy that implements Proposal 2 in the dedicated to messages google doc: https://docs.google.com/document/d/1-TsnJTs5puAfakv9YWbyppgGXqVjNa_g0jY9bYzaPBg/edit#heading=h.qqa30e5sck9s

See section 4.3.6

**Comment by aronschatz** [comment]
I like proposal 2. I also don't think we need to sound the alarms and can just get this in the next point release of the spec since nobody has implemented v1.0 (probably).

**Comment by gasperk** [comment]
#2 makes sense to me, though I think we intentionally put the player in control here for streaming environments, where the video ad _has to_ start playing and can't wait for the creative to finish loading. I've read your edit but I don't fully understand how you've addressed this use case. I believe it's covered in Special Cases, though I'd argue those aren't really (going to be) special.

**Comment by ryanthompson591** [comment]
Talked with Andre, in meeting.  He feels this is resolved.
