### ISSUE TITLE
Terms "video" vs. "media" inconsistencies

### ISSUE THREAD

**Issue by andmig** [InteractiveAdvertisingBureau/SIMID#292]
Unfortunately, we failed to replace all instances of the term `video` with `media`. This includes, most concerning, API naming conventions. 

Ideally, the spec should be accurately aligned with the intent of broadening media type coverage where in-stream (VAST, SIMID, etc.) ads are suitable for serving both video and audio ads.

**Comment by ryanthompson591** [comment]
there is only one hard to deprecate api in 1.0.

getVideoState

We discussed in meeting - We could deprecate getVideoState in favor of getMediaState for version 1.1.

**Comment by streiko** [comment]
I came across some `videoDimensions` in Player:init and Player:resize. Will it change to `mediaDimensions` too?

**Comment by amitshetty** [comment]
we probably should

**Comment by mimidden** [comment]
Could cause backwards compatibility issues, group has decided to hold off on changes for now.
