### ISSUE TITLE
SIMID:Player:appBackgrounding >> resolve 

### ISSUE THREAD

**Issue by andmig** [InteractiveAdvertisingBureau/SIMID#298]
Neither `resolve` seems to support specific use case, nor SIMID offers details of how the player handles `resolve`.

Suggestion: remove `SIMID:Player:appBackgrounding` `resolve` from the spec.

**Comment by aronschatz** [comment]
I was going through this and agree with this proposal.

**Comment by andmig** [comment]
Remove resolve.
