### ISSUE TITLE
Suggest sandbox attributes as part of the spec

### ISSUE THREAD

**Issue by ryanthompson591** [InteractiveAdvertisingBureau/SIMID#302]
Since the simid creative is responsible for opening tabs on clickthrough the iframe sandbox should have the following attributes.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

allow-forms 
allow-pointer-lock
allow-popups
allow-same-origin
allow-popups-to-escape-sandbox
allow-scripts
allow-top-navigation-by-user-activation

We should tell creatives not to expect these permissions:
allow-downloads-without-user-activation
allow-orientation-lock
allow-top-navigation

**Comment by ryanthompson591** [comment]
David - We could put this code into the sample code, instead of the spec.
Andre - Perhaps we could have a non versioned best practices document separate from the spec with this sort of information. 

Error codes could also fit into a living updating doc (a separate one).

**Comment by mimidden** [comment]
Not enough necessity to put in spec at this point. Could be sample code, but should be an implementation detail.
