### ISSUE TITLE
Add SIMID to the API Frameworks section of IAB adcom model

### ISSUE THREAD

**Issue by ryanthompson591** [InteractiveAdvertisingBureau/SIMID#303]
https://iabtechlab.com/~iabtec5/wp-content/uploads/2017/09/AdCOM-The-Advertising-Common-Object-Model.pdf

List 3: API Frameworks\

Should include SIMID though it currently does not.

**Comment by aronschatz** [comment]
https://github.com/InteractiveAdvertisingBureau/AdCOM/pull/10

Governance is still a problem in Adcom and has not been resolved. The PR has been there since April.

**Comment by amitshetty** [comment]
Done.
