### ISSUE TITLE
Skip offset parameter on init

### ISSUE THREAD

**Issue by ryanthompson591** [InteractiveAdvertisingBureau/SIMID#304]
If the player decides that with SIMID ads it wants them to handle skip, the player should be able to tell the creative what the skip offset from VAST was.

If the skippable value is creative Handles, we should pass through the skip offset to the skippable ad.

**Comment by ryanthompson591** [comment]
Discussed in meeting:
- A publisher is able to decide to skip or not skip. So therefor, it might be worth forwarding this information.

Another consideration:
It is possible that the SIMID ad could pass these values via parameters if it wants to skip.

We could punt on this issue for now until we have a wider conversation.  Specifically:
1. We need to know if the skip offset feature is going to be deprecated from VAST.

What we think should happen:
Instead of adding many parameters in SIMID, we could tell ad creators to pass this information in the ad parameters. The player can still pass AD_HANDLES as the skip param.

**Comment by mimidden** [comment]
Can be an optional parameter called Player:skipOffset
