### ISSUE TITLE
Session initialization :: failure to post createSession message

### ISSUE THREAD

**Issue by andmig** [InteractiveAdvertisingBureau/SIMID#310]
The spec does not discuss how the player should handle the situations when the creative fails to post `createSession` message.

There are three possible options:

Scenario A:
step 1: Player establishes timeout --> 
step 2: timeout expires --> 
step 3: player unloads creative --> 
step 4: player reports error tracker with the corresponding code -->
step 4: player proceeds with ad-media rendering

Scenario B (recommended but not enforceable in all cases):
steps 1 through 4 as in scenario A -->
step 5: Player aborts ad execution.

Scenario C:
step 1: player establishes timeout -->
step 2: timeout expires -->
step 3: player reports error tracker -->
step 4: player starts media playback -->
step 5: player retains creative until the end of the ad BUT does not send any messages to it -->
step 6: creative posts createSession message -->
step 7: player goest through initialization flow and starts posting messages to and accepting message from the creative.

step 8: ad ends but creative in unresponsive - just unload creative.

Scenario C is aligned with how we handle delayed creative loading now.

Thoughts?

**Comment by amitshetty** [comment]
If createsession is not established in a reasonable period of time... error and unload iframe?

**Comment by ryanthompson591** [comment]
This is discussed in issue #312.

**Comment by andmig** [comment]
Hi Amit,

Not exactly. We discerned that non-communicative creative will be retained
by the player until the media playback end in case it (creative)
resurrects. Creative will stay hidden unless it resumes being compliant
with the flow.

This is except for the Creative:fatalError message; in such case, the
player kills the creative no questions asked.

Ryan and I chew on the flow in great detail taking into consideration not
technical but business aspects as well. One of the positives to simplify
the requirements is that it appeases publishers in the sense that they will
not lose as many impressions as they do with VPAID. But this is not the
most important reason for the approach.

Andrei
