### ISSUE TITLE
Keep fullscreen case consistent in the spec

### ISSUE THREAD

**Issue by ryanthompson591** [InteractiveAdvertisingBureau/SIMID#311]
Sometimes the spec uses fullscreen and other time fullScreen.  We should only have one version throughout the spec.  Since version 1.0 doesn't have much use yet let's fix this into version 1.01.

**Comment by ryanthompson591** [comment]
Talked with andre. We will use fullscreen everywhere in 1.01

**Comment by ryanthompson591** [comment]
Other API changes

appBackgrounding -> appBackgrounded
appForegrounding -> appForegrounded
getVideoState-> getMediaState

Andre to add this to his PR.

**Comment by andmig** [comment]
@ryanthompson591, @amitshetty, and @aronschatz 
I am also changing:
requestFullScreen -> requestFullscreen
requestExitFullScreen -> requestExtiFullscreen

Do we agree?

**Comment by amitshetty** [comment]
Makes sense.

**Comment by aronschatz** [comment]
Agree.
