### ISSUE TITLE
environmentData -> variableDurationRequired

### ISSUE THREAD

**Issue by pietermees** [InteractiveAdvertisingBureau/SIMID#32]
**FreeWheel TV**
What is `variableDurationRequired`? Sourced from the "variableDuration" attribute of the `<InteractiveCreativeFile>` node in VAST?

**Pieter Mees**
Does this mean that XML attribute is an enum that can be set to `required`?

**Comment by ryanthompson591** [comment]
I think we discussed this and are keeping it similar to vast.
