### ISSUE TITLE
Response to app backgrounded with resolve deprecated?

### ISSUE THREAD

**Issue by ryanthompson591** [InteractiveAdvertisingBureau/SIMID#330]
Why is this deprecated?  I think it's fine to have the player give a best effort to listen for resolve.  Let's resolve this before releasing 1.0.1

**Comment by ryanthompson591** [comment]
Andre and I had a discussion about this.  Basically, we need a tie breaker.

If we decide to deprecate the reason is that the ad cannot take any action that the app should wait for, and this appBackgrounded should be information only.

If we decide to keep (or punt until a future release) it will be because the creative may wish to take some action during the lifespan of the backgrounding hook.

**Comment by ryanthompson591** [comment]
We decided to punt on deprecating this.

So remove the deprecation language.

**Comment by andmig** [comment]
Sorry, but we need to revisit. The spec language states: _"when the app moves to the background, the player posts a SIMID:Player:appBackgrounded message"_

It resumes that player posts appBackgounrde **AFTER** app was backgrounder. If this a correct description of the message - resolve is immaterial as the app went to background already and there is nothing app can do about it. Hence, resolve is makes no sense. We can still retain resolve but it would be optional?

On the other hand, if the player is willing to delay backgrounding, we need to change the message language to acknowledge the fact that backgrounding has not occurred yet. In such case the name of the message becomes awkward as it is in a past tense.
