### ISSUE TITLE
Normal Player:startCreative Sequence - Steps and diagram pics don't match

### ISSUE THREAD

**Issue by ryanthompson591** [InteractiveAdvertisingBureau/SIMID#332]
For example 

Step 1. Media playback begins.

Is the step but on the diagram that is the startCreative message.

Diagram should be fixed.

A separate thought. If we don't put step numbers in the workflow, we can have the diagram just be a picture. The the steps can be text (and easier to edit) instead of images.

**Comment by andmig** [comment]
The diagram is fixed and PR created.

**Comment by ryanthompson591** [comment]
Thanks Andre!
