### ISSUE TITLE
Add new macros in vast to indicate simid support

### ISSUE THREAD

**Issue by ryanthompson591** [InteractiveAdvertisingBureau/SIMID#339]
I think we should suggest these macros to the VAST committee.

INTERACTIVE_VARIABLEDURATION

-1 = Unknown
0 = not supported, player will not allow video pause
1 = supported

INTERACTIVE_RESIZE

-1= unknow
0 = player and ad resize not allowed
1 = player and ad resize allowed

**Comment by ryanthompson591** [comment]
We talked and there are a few more possiblities.

1. Piggyback on the poorly written PLAYERCAPABILITIES macro.
Add these values to the list:
NO_SIMID_VARIABLE_DURATION
SIMID_VARIABLE_DURATION
NO_SIMID_RESIZE
SIMID_RESIZE

If the value is not populated it would be considered to be unknown.

2. Do the same as option 1, except in a SIMIDCAPABILITIES macro.

**Comment by aronschatz** [comment]
My suggestion is to remove references to SIMID for any VAST macros. These are covered in AdCOM already and all we'd need to do is make macros to cover what's missing from VAST right now.

VARIABLEDURATION
RESIZE

For the SIMID version, we can align to the API Frameworks of AdCOM or just have a distinct (VAST only) signal. The thought is that if people buying and selling need this signal, let's get it into AdCOM.

**Comment by aronschatz** [comment]
I am leaning towards putting in any version information into AdCOM, directly so buyers and sellers can communicate this. Will discuss next steps on the call.

**Comment by andmig** [comment]
We need to consider whether the player must communicate its capacity to expand non-linear ads. Nonlinear ad expansion requires pausing the main content. 

We have two options: 

1. SIMIDVARIABLEDURATION macro also describes expansion capacity. If the value is 0 - the player will not expand nonlinear ad.

1. We may want to introduce a special macro, dedicated to the expansion capacity.
