### ISSUE TITLE
Create a resources section in the main page

### ISSUE THREAD

**Issue by ryanthompson591** [InteractiveAdvertisingBureau/SIMID#344]
I would be nice if the SIMID page linked to some resources like the simid tag here:
https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags

Also, maybe it would be cool to call out players that support SIMID.

It would be great if we took our simid samples and wrapped them into VAST so they could be served as VAST and players could experiment with them.

**Comment by gopalswamy12345** [comment]
Yes.. a sample VAST integration will help...

**Comment by mimidden** [comment]
No one wants to develop/maintain this at the moment.
