### ISSUE TITLE
Add a nonlinear duration to this initialize method

### ISSUE THREAD

**Issue by ryanthompson591** [InteractiveAdvertisingBureau/SIMID#382]
Non linear ads have no way of knowing what their duration is unless the player tells them.

Proposal:
The initialize message creativeData object should have a duration parameter. Or a nonlinearDuration parameter.

The player should terminate the creative once the duration is reached.

This should be the same as the value passed in by the minSuggestedDuration field in the VAST request.

See:
https://interactiveadvertisingbureau.github.io/SIMID/#simid-player-init

**Comment by mimidden** [comment]
Augment copy to that the player might change suggested duration

**Comment by ryanthompson591** [comment]
This is added.
