### ISSUE TITLE
Error codes are confusing pr redundant.

### ISSUE THREAD

**Issue by andmig** [InteractiveAdvertisingBureau/SIMID#401]
We should revisit error codes. Some of them seem to describe the same matters. For example, code1105  states:
1105 | Request for expand not honored. | The creative requested to expand but the player did not allow it. 

Meanwhile, several codes in with 12XX numbers are introduced to describe nonlinear expansion use cases.

**Comment by aronschatz** [comment]
Change media playback window to media player. Will submit a PR.

**Comment by aronschatz** [comment]
#410
