### ISSUE TITLE
Nonlinear expand and collapse message

### ISSUE THREAD

**Issue by streiko** [InteractiveAdvertisingBureau/SIMID#406]
What are the correct messages for expanding and collapsing a Nonlinear SIMID Creative?

SIMID Definition says `Creative:expandNonlinear` and `Creative:collapseNonlinear` while the Creative Examples are using `Creative:requestExpand` and `Creative:requestCollapse`

**Comment by ryanthompson591** [comment]
Good catch.  I will try to bring this up next meeting.  The sample code and spec were developed in parallel.

If it's up to me, these should not be requests but rather the player should be able to expand and collapse.  It is likely the sample code that needs fixing.

**Comment by mimidden** [comment]
Committee decided to change the sample code because the spec is correct.
