### ISSUE TITLE
Ryan:  Reasonable timeout for unresponsive ad

### ISSUE THREAD

**Issue by mtumi** [InteractiveAdvertisingBureau/SIMID#75]
From: 2.5.7 How to Handle Errors 
Original text: The player may error out if the ad does not respond with AdLoaded and AdStarted in a reasonable amount of time.

Ryan Thompson
I suggest 2 seconds, but I don't know if we should put that in the spec.

Andrei Andreev
7:25 PM Mar 4
VPAID traditionally doesn't specify timeout value. It just states that player should establish reasonable wait time. Heuristically players landed at about 4 second timeout.

However, we may want to consider specification of max value. Frankly, nowadays even one second is too excessive for the purposes interactive ad component serves. 

The reality is that long timeouts serve objectives of ad engaging in elective, not directly related to interactivity and user experience enhancements activities like loading of verification scripts or trading.

Even with verification scripts loading it takes not more than 500 ms to subload all the modules.

Ideally, timeout should be dictated by only one factor - latencies related to loading interactive experience supporting scripts and assets. This really takes a few hundred milliseconds.

Also, from player perspective, perhaps, timeouts are significant mostly in pre-rolls cases. In other ad positioning relative to main content situations players should establish ad/assets preloading routines.

Gasper Kozak
2:13 PM Mar 21
If you want to count all interactive assets under AdLoaded, this can easily go beyond 2s, especially on mobile. Some players have limits, but are much higher (Google's default is 8 seconds I think). We learned that some creative ad servers get around that by emitting AdLoaded before all the assets are actually loaded.

**Comment by ryanthompson591** [comment]
This is discussed here.  I'm closing this so we don't have too many duplicates.
#255
