### ISSUE TITLE
Freewheel TV, Pieter:  Comments on fullscreen

### ISSUE THREAD

**Issue by mtumi** [InteractiveAdvertisingBureau/SIMID#81]
From supported video proxy methods.  may no longer be relevant with postmessage approach 

FreeWheel TV
Does this mean in HTML5 environment the player should set the fullscreen attribute of the video element? If yes, the interactive layer will be hidden in fullscreen mode. Is that expected behavior?

Pieter Mees
Plus that the browser will not see these asynchronous events as user-initiated, which could prevent the player from entering fullscreen?

**Comment by ryanthompson591** [comment]
We think full screen is addressed in the current spec. Closing as outdated.
