### ISSUE TITLE
Clarification of OMSDK Integration with SIVIC

### ISSUE THREAD

**Issue by ravivooda** [InteractiveAdvertisingBureau/SIMID#95]
Should we jot down how the SIVIC ad (as a whole) should be handled by the publisher for OMSDK for verification purposes.

Suggestion:

1. Register the player as the ad View.
2. Register the SIVIC Interactive creative part (iFrame) as a friendly obstruction. 

Questions:

1. Would there be any other views created in the ad's life span?

**Comment by ryanthompson591** [comment]
We discussed this in the meeting and can close this for now.  OMID will need to figure this out.
