### ISSUE TITLE
Implement message API library

### ISSUE THREAD

**Issue by pietermees** [InteractiveAdvertisingBureau/SIMID#98]
Update [Burrata](https://github.com/timdp/burrata) - our existing draft message API library - with [the latest spec changes](https://github.com/InteractiveAdvertisingBureau/SIVIC/issues/83) so it can be used in a SIVIC prototype.

**Comment by ryanthompson591** [comment]
I want to close this now that we have a sample implementation.  I prefer we open a new more specific issue if I'm missing something.
